version: '3.1'

services:
  redis:
    image: redis:8.0
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    command: ["redis-server", "--appendonly", "no"]

  mongo:
    image: mongo:8.0.15
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: muP4woo9Aidiph2jeX8u
    command: --auth

  mysql:
    image: mysql:8.0.40
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: muP4woo9Aidiph2jeX8u
      
  arcade:
    image: go-arcade/arcade:latest
    container_name: arcade
    restart: always
    ports:
      - 8080:8080
      - 9090:9090
      - 8082:8082
      - 8083:8083
    volumes:
      - ./conf.d:/conf.d
  
  arcade-agent:
    image: go-arcade/arcade-agent:latest
    container_name: arcade-agent
    restart: always
    ports:
      - 8081:8081
      - 8084:8084
      - 8085:8085
      - 8086:8086
    volumes:
      - ./conf.d:/conf.d
